language: generic
sudo: true
addons:
   hosts:
       - travis
   hostname: travis
env:
   - PYTHON_VERSION="2.7"
   - PYTHON_VERSION="3.4"
   - PYTHON_VERSION="3.5"
   - PYTHON_VERSION="3.6"
before_install:
   # Get the tag if it wasn't provided. Travis doesn't provide this if it isn't a tagged build.
   - if [ -z $TRAVIS_TAG ]; then TRAVIS_TAG=`git tag --contains` ; fi
   - echo $TRAVIS_TAG
   # Move out of git directory to build root.
   - cd ../..
   - pwd
install:
   # Download and configure conda.
   - wget http://repo.continuum.io/miniconda/Miniconda`echo ${PYTHON_VERSION:0:1}`-latest-Linux-x86_64.sh -O miniconda.sh
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - conda config --set always_yes yes
   - conda config --set show_channel_urls True
   - conda config --add channels conda-forge
   - source activate root
   - conda update --all
   # Fix root environment to have the correct Python version.
   - touch $HOME/miniconda/conda-meta/pinned
   - echo "python ${PYTHON_VERSION}.*" >> $HOME/miniconda/conda-meta/pinned
   - conda install python=$PYTHON_VERSION
   # Install basic conda dependencies.
   - conda install conda-build
   # Build the conda package for splauncher.
   - cd $TRAVIS_REPO_SLUG
   - VERSION=`python setup.py --version`
   - echo $VERSION
   - python setup.py bdist_conda
   # Setup environment for splauncher and install it with all dependencies.
   - conda create --use-local -n testenv python=$PYTHON_VERSION splauncher==$VERSION
   - source activate testenv
   # Install DRMAA with Python support.
   - .travis_scripts/install_sge.sh
   - export SGE_ROOT=/var/lib/gridengine
   - export SGE_CELL=default
   - export DRMAA_LIBRARY_PATH=/usr/lib/libdrmaa.so.1.0
   - conda install drmaa
   # Install sphinx and friends to build documentation.
   - conda install sphinx
   - conda install cloud_sptheme
   # Install coverage to generate test coverage results.
   # Also, install docstring-coverage to get information about documentation coverage.
   - conda install nose-timer
   - conda install coverage
   - conda install docstring-coverage || true
   # Clean up downloads as there are quite a few and they waste space/memory.
   - sudo apt-get clean
   - conda clean -tipsy
   - rm -rfv $HOME/.cache/pip
script:
   # Clear old coverage.
   - coverage erase
   # Run tests.
   - python setup.py nosetests --with-timer
   # Build documentation.
   - python setup.py build_sphinx
   # Get info on docstring coverage.
   - (hash docstring-coverage && docstring-coverage splauncher | tee .docstring-coverage) || true
after_success:
   # Workaround for odd coveralls behavior on Python 3.6.
   - conda create -y -n dplenv python="3.5" python-coveralls
   - source activate dplenv
   # Submit results to coveralls.io.
   - coveralls
notifications:
  email:
    - $TO_EMAIL
